import type { Metadata, Viewport } from "next";
import { A, AnchorList } from '@catalyse/simple-components';
import { AddBodyClass } from '../components/AddBodyClass';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export const viewport: Viewport = {
  themeColor: '#0b0c0c'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AddBodyClass />
        <AnchorList
          items={[
            {
              href: "/",
              text: "Home"
            },
            {
              href: "/one",
              text: "One"
            },
            {
              href: "/one/two",
              text: "Two"
            },
            {
              href: "/three",
              text: "Three"
            },
            {
              href: "/four",
              text: "Four"
            }
          ]}
        />
        <A href="/feedback">Provide feedback</A>
        {children}
      </body>
    </html>
  );
}
